"""Add confidentiality to case

Revision ID: eb6556176f6e
Revises: 
Create Date: 2026-08-23 09:45:10.725169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb6556176f6e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_otps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('otp_code', sa.String(length=6), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_otps_case_id'), 'access_otps', ['case_id'], unique=False)
    op.add_column('cases', sa.Column('confidentiality_level', sa.String(), server_default='normal', nullable=False))
    op.add_column('cases', sa.Column('access_verified', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'access_verified')
    op.drop_column('cases', 'confidentiality_level')
    op.drop_index(op.f('ix_access_otps_case_id'), table_name='access_otps')
    op.drop_table('access_otps')
    # ### end Alembic commands ###
